import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Link from 'next/link';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Prueba Fetching</h1>
      <Link href='react-query'><p><a style={{ cursor: 'pointer' }}>React-Query example</a></p></Link>
      <Link href='ssr'><p><a style={{ cursor: 'pointer' }}>Server Side Rendering Example</a></p></Link>

    </div>
  )
}
